pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                // We simulate putting this in an artifact repository (e.g. Nexus)
                sh 'mkdir -p /var/nexus/artifacts/'
                sh 'cp target/debug.war /var/nexus/artifacts/debug.war'
            }
        }
    }
}
