#!/bin/bash -xe

LOG=/var/log/configure_ec2_instance.log

sudo touch $LOG
sudo chown ec2-user $LOG
echo " [`basename "$0"`]: Starting configuration routine" | tee -a $LOG
sudo pip install ansible | tee -a $LOG
sudo yum install -y git | tee -a $LOG
sudo -u ec2-user /usr/bin/git clone https://github.com/cloudomatic/ArtOfWar /home/ec2-user/ArtOfWar | tee -a $LOG
sudo -u ec2-user /usr/local/bin/ansible-playbook /home/ec2-user/ArtOfWar/install/ansible/install.yaml -vvv >> /home/ec2-user/ansible_install.out 2>>  /home/ec2-user/ansible_install.err 

