

- name: Install Apache Tomcat with the target WAR
  hosts: localhost
  vars:
    maven_version_label: apache-maven-3.5.4
    maven_download_url: http://us.mirrors.quenda.co/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
    tomcat_version_label: apache-tomcat-8.5.34
    tomcat_download_url: http://apache.mirrors.pair.com/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.zip

  tasks:

  - name: Install OS packages
    yum: 
      name: "{{ item }}"
      state: present
    become: true
    with_items:
     - git
     - unzip
     - java-1.8.0-devel

  # The current AWS package for Maven seems to revert back to JDK 1.7 so a manual download is required
  - name: Download Maven
    get_url:
      url: "{{ maven_download_url }}"
      dest: "/var/tmp/{{ maven_version_label }}.zip"

  - name: Download Apache Tomcat
    get_url:
      url: "{{ tomcat_download_url }}"
      dest: "/var/tmp/{{ tomcat_version_label }}.zip"

  - name: Make Java 1.8 the default JDK
    become: true
    alternatives: 
      link: /usr/bin/java
      name: java
      path: /usr/lib/jvm/java-1.8.0/bin/java
    alternatives:
      link: /usr/bin/javac
      name: javac
      path: /usr/lib/jvm/java-1.8.0/bin/javac

  - name: Unpack Maven
    become: true
    unarchive:
      src: "/var/tmp/{{ maven_version_label }}.zip"
      dest: /opt
      mode: ugo+rx
      owner: ec2-user
      group: ec2-user
      creates: "/opt/{{ maven_version_label }}.zip"

  - name: Link Maven version as default
    become: true
    file:
      src: "/opt/{{ maven_version_label }}"
      dest: /opt/maven
      state: link

  - name: Set Maven path
    become: true
    copy:
      dest: /etc/profile.d/maven.sh
      content: 'PATH=$PATH:/opt/maven/bin'

  - name: Unpack Tomcat
    become: true
    unarchive:
      src: "/var/tmp/{{ tomcat_version_label }}.zip"
      creates: "/opt/{{ tomcat_version_label }}.zip"
      dest: /opt
      mode: ugo+rx
      owner: ec2-user
      group: ec2-user

  - name: Link Tomcat version as default
    become: true
    file:
      src: "/opt/{{ tomcat_version_label }}"
      dest: /opt/apache-tomcat
      state: link
  
  - name: Build WAR
    command: mvn clean install
    args:
      chdir: /home/ec2-user/ArtOfWar
      creates: /home/ec2-user/ArtOfWar/target/debug.war

  - name: Copy WAR to Tomcat
    copy: 
      src:  /home/ec2-user/ArtOfWar/target/debug.war
      dest: /opt/apache-tomcat/webapps/debug.war
      mode: ugo+rx

  - name: Start Tomcat
    command: nohup /opt/apache-tomcat/bin/startup.sh >> /opt/apache-tomcat/logs/startup.log &
    
