#!/bin/sh

#
# Program to install a basic JEE server (Tomcat) with the target WAR file
#
#

target_war=

# Check for ansible packages on the local VM and install if necessary


# Run the Ansible playbook
